import './styles/globals.css'
import { Josefin_Sans, Merriweather } from 'next/font/google';


const oswald = Josefin_Sans({ subsets: ['latin'], weight: ['300', '400', '600', '700'], });


export const metadata = {
  title: 'My Portfolio',
  description: 'Generated by Hadiul',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={oswald.className}>{children}</body>
    </html>
  )
}
